### ISSUE TITLE
能用mixins吗？

### ISSUE THREAD

**Issue by S1ow** [linjc/mini-stores#1]
能用mixins吗？

**Comment by linjc** [comment]
可以，store是个对象，任何地方都可以引入读取，可通过store.update()触发页面更新，只需确保当前页面是通过create.Page创建即可。

**Comment by linjc** [comment]
可以，store是个对象，任何地方都可以引入读取，然后可使用store.update()触发页面更新，只需确保当前页面是通过create.Page创建即可。
