### ISSUE TITLE
1.1.5(最新版本)在京东小程序环境不好用

### ISSUE THREAD

**Issue by Eecnal** [linjc/mini-stores#6]
上截图
开发工具：京东小程序官方IDE 版本为1.9.9

1、
<img width="1186" alt="image" src="https://github.com/linjc/mini-stores/assets/91534191/f75a09cd-5567-4058-b653-438e2f2cdd4b">
npm包为最新版本，并且构建了npm包

2、
<img width="1214" alt="image" src="https://github.com/linjc/mini-stores/assets/91534191/a938e6bc-9d93-4a74-aa97-023d43c40434">
store文件也创建了，import导入的（换成require导入也是不好用），注意data里popup对象，下面会提到

3、
<img width="818" alt="image" src="https://github.com/linjc/mini-stores/assets/91534191/9bcc1f63-aa70-43fd-bcf4-747a91a6b723">
这是具体页面绑定store情况（根据官方文档所写）注意那个handleClosePopup方法，下面会提到

4、
<img width="2191" alt="image" src="https://github.com/linjc/mini-stores/assets/91534191/eb66b39d-1b99-42a4-8036-7f9ec45b4b92">
这是具体页面开始测试最新版store是否好用，根据store文件data有个popup对象的设置，出现了上图中的弹窗，但是这个弹窗我绑定了一个关闭方法：handleClosePopup，我点击关闭按钮却没反应，根本无法与store文件的setClosePopup方法进行联动，不仅如此，图上的这个弹窗，在我手动打开的时候（也就是说通过点击事件调用store文件里的setOpenPopup方法），也无法打开

综上所述，最新版的mini-stores安装包，在京东小程序貌似不太好使，如果您发现我这边儿写的有问题，还请指正

**Comment by Eecnal** [comment]
我这边儿一直在使用您的mini-stores插件，我原先使用的1.0.5的版本，在这个版本下，使用原来的官网写法，是完全好用的

**Comment by linjc** [comment]
@Eecnal 你单独运行examples/jd样例试试是否正常，我这边是正常的

**Comment by Eecnal** [comment]
我找到问题了......

**Comment by Eecnal** [comment]
我找到问题了

我在更新最新版mini-store插件的时候，除了按照官网写法修改了之外，只更改了pages/home/下的新写法，但是pages下面还有七八个页面，在这七八个页面的js中，我还是用之前的写法 create.Pages(stores,{})，所以就导致了我home下改的新版也不好使.....

然后我新建了一个项目，重新引用最新版的插件，就没问题了

这个bug我真的是，脑瓜疼

**Comment by linjc** [comment]
@Eecnal 目前新方案和老方案是相互独立的，单独使用都可以，但确实不支持两种方案同时使用。
