### ISSUE TITLE
感觉update可以省去

### ISSUE THREAD

**Issue by 1075488066** [linjc/mini-stores#8]
update直接改成响应式调用不更好，直接在set中调用update。

**Comment by linjc** [comment]
set中调用存在性能问题，且对后添加的属性不生效，存在不可控因素。-- 个人觉得。

**Comment by 1075488066** [comment]
> set中调用存在性能问题，且对后添加的属性不生效，存在不可控因素。-- 个人觉得。

你可以参考一下ahooks的useReative的代码用proxy实现

**Comment by linjc** [comment]
Proxy是不错的方向，等工作没那么忙的时候，考虑从这方面迭代。
